post http://localhost:3001/api/users
Content-Type: application/json



{
  "username": "mluukkai",
  "name": "Matti Luukkainen",
  "password": "mluukkai"
}

###for login

POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "mluukkai",
  "password": "mluukkai"
}

